[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
glyph_offset = { x = 0, y = 0 }
normal.family = "IosevkaNerdFontMono"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "IosevkaNerdFontMono"
style = "Bold"

[font.italic]
family = "IosevkaNerdFontMono"
style = "Italic"

[keyboard]
bindings = [ 
  { key = "T", mods = "Control", chars = "\u0002c" },        # create new window(aka tab)
  { key = "T", mods = "Control|Shift", chars = "\u0002!" },  # break pane into new window

  { key = "W", mods = "Control", chars = "\u0002x" },        # close window/pane
  { key = "N", mods = "Control|Shift", chars = "\u0002N" },        # open Floax
  #{ key = "W", mods = "Control|Shift", chars = "\u0002w" },  # list windows
  { key = "W", mods = "Control", action = "Quit"},           #Quit Session

  { key = "S", mods = "Control", chars = "\u0002%" },        # split window/pane vertically
  { key = "S", mods = "Control|Shift", chars = "\u0002\"" }, # split window/pane horizontally

  { key = "R", mods = "Control|Shift", chars = "\u0002r" },  # source config file

  { key = ";", mods = "Control|Shift", chars = "\u0002;" },  # navigate over to last pane
  { key = ",", mods = "Control", chars = "\u0002," },        # rename the window 
  { key = "]", mods = "Control", chars = "\u0002]" },        # open sesh
  { key = "f", mods = "Control", chars = "zi\n" },             # open zi
]

[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  # -- Themes --
  "~/.config/alacritty/catppuccin-macchiato.toml", 
  #"~/.config/alacritty/nordic.toml", 
  # "~/.config/alacritty/xcad.toml",
  # "~/.config/alacritty/dracula.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
  # "~/.config/alacritty/solarized_dark.toml",
  # "~/.config/alacritty/solarized-osaka.toml",
]
